version: '3.8'
services:
  incldev:
    restart: always
    image: picker24/pittpaccbox:latest
    container_name: incldev
    entrypoint: "bash -c 'jupyter lab --allow-root'"
    working_dir: "/software/"
    network_mode: "host"   
    environment:
      JUPYTER_TOKEN: "inclnotebook"
      JUPYTER_IP: "127.0.0.1"
      JUPYTER_PORT: "8893"
      JUPYTER_ALLOW_REMOTE_ACCESS: "True"
    volumes:
      - "${PWD}:/software/"
    ports:
      - "8893:8893"
